name: RELEASE
on:
  pull_request:
    branches: [develop]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: 🚚
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 🧱
        uses: actions/setup-node@v2
        with:
          node-version: lts/*

      - name: ➕
        run: npm ci

      - name: ✅
        run: npm test

      - name: 💚
        run: npm run build